server {
    listen 80;

    location /platformer/ {
        proxy_pass http://platformer/;
        proxy_set_header Host $host;
    }

    location /pokemon/ {
        proxy_pass http://pokemon/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://portal/;
        proxy_set_header Host $host;
    }
}
