apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbct-game
  namespace: games
spec:
  ingressClassName: traefik
  rules:
    - host: danglol240.id.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dbct-game
                port:
                  number: 80
